# Generated by Django 5.2.10 on 2026-01-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("size_range", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("silhouette", models.CharField(blank=True, max_length=120)),
                ("neckline", models.CharField(blank=True, max_length=120)),
                ("fabric", models.CharField(blank=True, max_length=120)),
                ("style_tags", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dresses",
                        to="shops.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DressImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="dress_images/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "dress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.dress",
                    ),
                ),
            ],
        ),
    ]
